language: go

go:
  - 1.3
  - 1.4
  - tip

before_install:
  - go get github.com/axw/gocov/gocov
  - go get github.com/mattn/goveralls

install:
  - go get -t -v ./...

script:
  - go test -v -cover ./...

matrix:
  allow_failures:
    - go: tip
